---
- name: Install Ngixx
  hosts: backend_servers
  become: yes

  vars:
   source_file: ./nginx_front/default
   dest_file: /etc/nginx/sites-available
   src: ./nginx_front/index.php
   dst: /var/www/html/

  tasks:

   - name: Update repositories
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

   - name: Install Nginx, php-fpm
     apt: name={{ item }} state=latest
     loop:
             - nginx
             - php-fpm
             - php-mbstring 
             - php-xml

   - name: Add to startup
     service:
      name: nginx
      state: started
      enabled: yes
     
   - name: Copy Nginx config
     copy: src={{ source_file }} dest={{ dest_file }} mode=644

   - name: Copy index.php
     copy: src={{ src }} dest={{ dst }} mode=644

   - name: Restart Nginx
     service:
      name: nginx
      state: restarted

