---
- name: Install Nginx && PHP && MYSQL to EC2 instance
  hosts: backend_servers
  become: yes
  

  vars_files:
    - vars/credentials.yaml

  vars:
    src_sql: ./templates
    dst_sql: ~/.my.cnf
  
### Copy config Nginx with phpmyadmin location

    source_file: ./nginx_back/default
    dest_file: /etc/nginx/sites-available

  ### Copy index.php

    src: ./nginx_back/index.php
    dst: /var/www/html/

  ### Copy config-db.php for phpmyadmin

    src_pma: ./nginx_back/config-db.php
    dst_pma: /etc/phpmyadmin


  tasks:

  - name: Update repositories
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600


  - name: Install Nginx, php-fpm
    apt: name={{ item }} state=present  # present
    loop:     
         
         - nginx
         - php-fpm
         - php-mbstring 
         - php-xml
         - mysql-server
         - mysql-client
         - python3-pymysql
         - libmysqlclient-dev
         - phpmyadmin

  - name: Start & Enabel services
    service: name={{ item }} enabled=yes
    loop:
         - nginx
         - mysql



  - name: Copy Nginx config
    copy: src={{ source_file }} dest={{ dest_file }} mode=644

  - name: Copy index.php
    copy: src={{ src }} dest={{ dst }} mode=644

  - name: Copy phpmyadmin config
    copy: src={{ src_pma }} dest={{ dst_pma }} mode=644  

  - name: Set password for root user and enable remout access
    mysql_user:
     name: "root"
     password: "{{ mysql_root_pass }}"
     priv: '*.*:ALL,GRANT'
     host: 'localhost'
     login_unix_socket: /var/run/mysqld/mysqld.sock
     state: present
  
  
  
  - name: Copy the root credentials as .my.cnf file
    template: src={{ src_sql }}/root.cnf.j2 dest={{ dst_sql }} mode=0600


  - name: Start & Enabel services
    service: name={{ item }} state=restarted
    loop:
         - nginx
         - mysql  

  - name: "Create phpmyadmin user {{ pam_username }}"
    mysql_user:
     name: "{{ pam_username }}"
     password: "{{ pma_password }}"
     priv: '*.*:ALL'